// GENERATED by scripts/vendor-agent-harnesses.mjs from agent-harnesses.json — do not edit by hand.
// Source:  https://huggingface.co/api/agent-harnesses
// Fetched: 2026-09-16T03:30:25.306Z
// sha256:  32b984909e18ffccd0c94c9982cc4c2ee30be6955001379b7ea96b797252db9d (of the registry object)
//
// The Hugging Face agent-harness registry, vendored as a static table so
// detection needs no network and no parser. Order is the MATCH order: the
// first harness whose marker is present wins. Only env var NAMES and match
// patterns are here — `Match::Any` means "set to any non-empty value" and the
// value is never read for content.

use crate::telemetry::{Harness, Match};

/// Vars any harness may set to its own id (`AI_AGENT=claude-code`).
pub(crate) const STANDARD_ENV_VARS: &[&str] = &["AI_AGENT", "AGENT"];

/// Every label [`crate::telemetry::detect_agent_harness`] can return: one per
/// registry entry, in registry order, then the two sentinels.
#[rustfmt::skip]
pub const AGENT_HARNESSES: &[&str] = &[
    "antigravity",
    "augment_cli",
    "cline",
    "cowork",
    "claude_code",
    "codex",
    "crush",
    "gemini_cli",
    "github_copilot",
    "goose",
    "hermes",
    "hi",
    "kilo_code",
    "kiro",
    "openclaw",
    "sandbase_harness",
    "opencode",
    "pi",
    "replit",
    "trae",
    "vtcode",
    "warp",
    "zed",
    "cursor_cli",
    "cursor",
    "devin",
    "unknown",
    "none",
];

// One entry per line, as vendored: `#[rustfmt::skip]` keeps the generated
// text byte-stable so `--check` can diff it.
#[rustfmt::skip]
pub(crate) const REGISTRY: &[Harness] = &[
    Harness {
        id: "antigravity",
        label: "antigravity",
        env_vars: &[
            ("ANTIGRAVITY_AGENT", Match::Any),
        ],
    },
    Harness {
        id: "augment-cli",
        label: "augment_cli",
        env_vars: &[
            ("AUGMENT_AGENT", Match::Any),
        ],
    },
    Harness {
        id: "cline",
        label: "cline",
        env_vars: &[
            ("CLINE_ACTIVE", Match::Any),
        ],
    },
    Harness {
        id: "cowork",
        label: "cowork",
        env_vars: &[
            ("CLAUDE_CODE_IS_COWORK", Match::Any),
        ],
    },
    Harness {
        id: "claude-code",
        label: "claude_code",
        env_vars: &[
            ("CLAUDECODE", Match::Any),
            ("CLAUDE_CODE", Match::Any),
        ],
    },
    Harness {
        id: "codex",
        label: "codex",
        env_vars: &[
            ("CODEX_SANDBOX", Match::Any),
            ("CODEX_CI", Match::Any),
            ("CODEX_THREAD_ID", Match::Any),
        ],
    },
    Harness {
        id: "crush",
        label: "crush",
        env_vars: &[
            ("CRUSH", Match::Any),
        ],
    },
    Harness {
        id: "gemini-cli",
        label: "gemini_cli",
        env_vars: &[
            ("GEMINI_CLI", Match::Any),
        ],
    },
    Harness {
        id: "github-copilot",
        label: "github_copilot",
        env_vars: &[
            ("COPILOT_MODEL", Match::Any),
            ("COPILOT_ALLOW_ALL", Match::Any),
            ("COPILOT_GITHUB_TOKEN", Match::Any),
        ],
    },
    Harness {
        id: "goose",
        label: "goose",
        env_vars: &[
            ("GOOSE_TERMINAL", Match::Any),
        ],
    },
    Harness {
        id: "hermes-agent",
        label: "hermes",
        env_vars: &[
            ("HERMES_SESSION_ID", Match::Any),
        ],
    },
    Harness {
        id: "hi",
        label: "hi",
        env_vars: &[],
    },
    Harness {
        id: "kilo-code",
        label: "kilo_code",
        env_vars: &[
            ("KILOCODE_FEATURE", Match::Any),
        ],
    },
    Harness {
        id: "kiro",
        label: "kiro",
        env_vars: &[
            ("AGENT_CONTEXT_OUT", Match::Any),
        ],
    },
    Harness {
        id: "openclaw",
        label: "openclaw",
        env_vars: &[
            ("OPENCLAW_SHELL", Match::Any),
        ],
    },
    Harness {
        id: "sandbase-harness",
        label: "sandbase_harness",
        env_vars: &[],
    },
    Harness {
        id: "opencode",
        label: "opencode",
        env_vars: &[
            ("OPENCODE_CLIENT", Match::Any),
        ],
    },
    Harness {
        id: "pi",
        label: "pi",
        env_vars: &[
            ("PI_CODING_AGENT", Match::Any),
        ],
    },
    Harness {
        id: "replit",
        label: "replit",
        env_vars: &[
            ("REPL_ID", Match::Any),
        ],
    },
    Harness {
        id: "trae",
        label: "trae",
        env_vars: &[
            ("TRAE_AI_SHELL_ID", Match::Any),
        ],
    },
    Harness {
        id: "vtcode",
        label: "vtcode",
        env_vars: &[
            ("VTCODE", Match::Exact("1")),
        ],
    },
    Harness {
        id: "warp",
        label: "warp",
        env_vars: &[
            ("TERM_PROGRAM", Match::Exact("WarpTerminal")),
        ],
    },
    Harness {
        id: "zed",
        label: "zed",
        env_vars: &[
            ("ZED_TERM", Match::Any),
        ],
    },
    Harness {
        id: "cursor-cli",
        label: "cursor_cli",
        env_vars: &[
            ("CURSOR_AGENT", Match::Any),
        ],
    },
    Harness {
        id: "cursor",
        label: "cursor",
        env_vars: &[
            ("CURSOR_TRACE_ID", Match::Any),
        ],
    },
    Harness {
        id: "devin",
        label: "devin",
        env_vars: &[],
    },
];
