//! Shared telemetry vocabulary.
//!
//! Lives here, in the crate every process already depends on, because two
//! processes emit the same events and they must agree on the values: the
//! daemon (`cosmonicd`'s `usage/` module — the one door to Amplitude) and the
//! MCP server (`cosmonic-mcp`), which hands its events to the daemon over the
//! socket. A second copy of `normalize_mcp_client` in the MCP crate would
//! silently drift into reporting a client the catalog's allowlist rejects,
//! dropping the event with nothing to show for it.
//!
//! Everything here is deliberately LOSSY. `clientInfo.name` is chosen by the
//! client and routinely carries a path or a hostname; a full version string is
//! a fingerprinting surface; a raw duration or count is a behavioural one. The
//! wire only ever sees a fixed enum, a major version, or a bucket label.

/// MCP client identities recognized from the `initialize` handshake's
/// `clientInfo.name`. Anything else maps to `other` — the raw string never
/// travels.
pub const MCP_CLIENTS: &[&str] = &[
    "claude_code",
    "claude_desktop",
    "cursor",
    "windsurf",
    "hermes",
    "openshell",
    "openclaw",
    "opencode",
    "codex",
    "vscode",
    "pi",
    "gemini_cli",
    "other",
];

/// Map an MCP `clientInfo.name` to the fixed [`MCP_CLIENTS`] enum.
///
/// Matching is case- and punctuation-insensitive, then a short alias table.
/// An unrecognized name is `other`, never the input.
pub fn normalize_mcp_client(raw: &str) -> &'static str {
    let norm: String = raw
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    let norm = norm.trim_matches('_').to_string();
    // Exact hits first, then a couple of well-known aliases.
    if let Some(c) = MCP_CLIENTS.iter().find(|c| **c == norm) {
        return c;
    }
    // The names below are what the agents ACTUALLY send (captured on the wire
    // for issue #527), not guesses: `codex-mcp-client`, `openclaw-bundle-mcp`,
    // and pi-mcp-adapter's `pi-mcp-<server name>`.
    match norm.as_str() {
        "claude_ai" | "claude" | "claudecode" => "claude_code",
        "claude_desktop_app" | "claude_for_desktop" => "claude_desktop",
        "cursor_vscode" | "cursor_ide" => "cursor",
        "visual_studio_code" | "vscode_mcp" | "code" => "vscode",
        "windsurf_ide" => "windsurf",
        "codex_mcp_client" | "codex_cli" => "codex",
        "openclaw_bundle_mcp" => "openclaw",
        "gemini" | "gemini_cli_mcp_client" => "gemini_cli",
        n if n.starts_with("pi_mcp_") => "pi",
        _ => "other",
    }
}

/// [`normalize_mcp_client`] over the whole `clientInfo`: the `name` first,
/// then the human-readable `title` (MCP 2025-06-18) when the name is one we
/// do not know. Codex sends `name: "codex-mcp-client", title: "Codex"`; a
/// client whose name is an SDK default (`"mcp"`) may still say who it is in
/// the title. Still an enum in, enum out — neither string travels.
pub fn normalize_mcp_client_info(name: &str, title: Option<&str>) -> &'static str {
    match normalize_mcp_client(name) {
        "other" => title.map_or("other", normalize_mcp_client),
        known => known,
    }
}

// ---- which agent launched us --------------------------------------------
//
// The second signal next to `clientInfo.name` (issue #527): an AI coding agent
// that spawns `cosmonic-mcp` / `cosmonicd mcp serve` / `cosmonic-stdio` leaves
// its own marker in the environment we inherit (`CLAUDECODE`,
// `CODEX_THREAD_ID`, `HERMES_SESSION_ID`, …). The Hugging Face client
// fingerprints agents the same way from a registry it maintains; ours is that
// registry, VENDORED (`agent_harnesses.rs`, regenerated by
// `scripts/vendor-agent-harnesses.mjs`) — never fetched at runtime.
//
// Presence-only, by construction: a `Match::Any` marker is tested for being
// set, an exact-pattern one for equality, and the label returned is always a
// member of [`AGENT_HARNESSES`]. Several markers are session ids and one is a
// token (`COPILOT_GITHUB_TOKEN`); none of their values ever leaves this
// function.

pub use crate::agent_harnesses::AGENT_HARNESSES;
use crate::agent_harnesses::{REGISTRY, STANDARD_ENV_VARS};

/// One registry entry. `id` is the upstream (kebab-case) id, `label` the
/// snake_case value that travels — folded onto [`MCP_CLIENTS`] spelling where
/// the two overlap so `client` and `harness` compare equal when they agree.
pub(crate) struct Harness {
    pub id: &'static str,
    pub label: &'static str,
    pub env_vars: &'static [(&'static str, Match)],
}

/// How a marker variable is tested. Only two entries upstream use `Exact`
/// (`VTCODE=1`, `TERM_PROGRAM=WarpTerminal`).
pub(crate) enum Match {
    /// Set to any non-empty value.
    Any,
    /// Equal to exactly this value.
    Exact(&'static str),
}

/// Markers observed on THIS product's surface that the upstream registry does
/// not list. The registry is calibrated for CLIs an agent runs from its shell
/// tool; an MCP server is spawned by a different code path and some agents
/// hand it a different environment (captured for issue #527, see
/// `docs/telemetry/AGENT-HARNESS.md`). Checked alongside the registry's own
/// markers for the same label, same presence-only rule. Send each upstream.
const LOCAL_MARKERS: &[(&str, &str, Match)] = &[
    // opencode 1.18 hands an MCP server `OPENCODE=1` (plus `AGENT=1`), not the
    // `OPENCODE_CLIENT` its shell exports. Without this the standard var
    // `AGENT=1` would label every opencode session `unknown`.
    ("opencode", "OPENCODE", Match::Any),
];

/// The label for "no agent marker present at all".
pub const HARNESS_NONE: &str = "none";
/// The label for "a standard var (`AI_AGENT`/`AGENT`) names a harness the
/// registry does not know" — the raw value never travels.
pub const HARNESS_UNKNOWN: &str = "unknown";

/// Which AI coding agent spawned this process, as a member of
/// [`AGENT_HARNESSES`] — never a raw env value.
///
/// Semantics match `huggingface_hub`'s `detect_agent()`: walk the registry in
/// order and return the first harness whose marker matches or whose id a
/// standard var equals; failing that, a standard var set to a case-variant of
/// a known id returns that harness, any other non-empty value is `unknown`,
/// and nothing set is `none`.
///
/// `env` is the environment as a lookup — `|k| std::env::var(k).ok()` in
/// production, a map in tests. It is a parameter so the tests never read the
/// real environment: our CI and our own dev loop run under a coding agent, and
/// a test that saw `CLAUDECODE` would pass or fail depending on who ran it.
pub fn detect_agent_harness(env: impl Fn(&str) -> Option<String>) -> &'static str {
    let standard: Vec<String> = STANDARD_ENV_VARS
        .iter()
        .filter_map(|v| env(v))
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
        .collect();

    let matches = |var: &str, pat: &Match| match env(var) {
        Some(v) if !v.is_empty() => match pat {
            Match::Any => true,
            Match::Exact(want) => v == *want,
        },
        _ => false,
    };
    for h in REGISTRY {
        let marked = h.env_vars.iter().any(|(var, pat)| matches(var, pat))
            || LOCAL_MARKERS
                .iter()
                .any(|(label, var, pat)| *label == h.label && matches(var, pat));
        if marked || standard.iter().any(|v| v == h.id) {
            return h.label;
        }
    }

    match standard.first() {
        None => HARNESS_NONE,
        Some(v) => {
            let lower = v.to_ascii_lowercase();
            REGISTRY
                .iter()
                .find(|h| h.id.eq_ignore_ascii_case(&lower))
                .map_or(HARNESS_UNKNOWN, |h| h.label)
        }
    }
}

/// [`detect_agent_harness`] over this process's real environment.
pub fn detect_agent_harness_from_env() -> &'static str {
    detect_agent_harness(|k| std::env::var(k).ok())
}

/// Registry entries whose marker is set by a terminal or an IDE for EVERY
/// shell it opens, not only when its agent is driving. They stay as labels
/// (the data is real: this session ran inside Warp), but they must not turn
/// on agent-only behaviour — Hugging Face's `--format auto` disabled colour
/// for every Warp user (huggingface/huggingface_hub#4860).
const AMBIENT_HARNESSES: &[&str] = &["warp", "zed", "cursor", "trae", "replit"];

/// Whether a detected label means an AI coding agent is the caller — the
/// gate for agent-facing behaviour (machine-readable output, no colour, a
/// harness-tuned instructions block). `unknown` counts: something announced
/// itself as an agent. `none` and the ambient terminal/IDE labels do not.
pub fn is_agent(harness: &str) -> bool {
    harness != HARNESS_NONE && !AMBIENT_HARNESSES.contains(&harness)
}

/// The MAJOR component of a semver-ish version string, or `"unknown"`.
/// Deliberately lossy: a full version is a fingerprinting surface.
pub fn version_major(raw: &str) -> String {
    raw.trim()
        .trim_start_matches('v')
        .split(['.', '-', '+'])
        .next()
        .filter(|s| !s.is_empty() && s.chars().all(|c| c.is_ascii_digit()))
        .unwrap_or("unknown")
        .to_string()
}

/// Session length: `<1m` / `1-10m` / `10-60m` / `1-8h` / `8h+`.
pub fn session_secs(secs: u64) -> &'static str {
    match secs {
        0..=59 => "<1m",
        60..=599 => "1-10m",
        600..=3_599 => "10-60m",
        3_600..=28_799 => "1-8h",
        _ => "8h+",
    }
}

/// Small counts: `0` / `1-5` / `6-20` / `21+`.
pub fn count_results(n: u64) -> &'static str {
    match n {
        0 => "0",
        1..=5 => "1-5",
        6..=20 => "6-20",
        _ => "21+",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unknown_client_never_leaks_its_raw_name() {
        // The whole point: clientInfo.name is attacker-controlled and often
        // carries a path or a hostname.
        for raw in [
            "/Users/someone/bin/weird-agent",
            "acme-internal-tool 1.2",
            "host.corp.example",
            "",
        ] {
            let got = normalize_mcp_client(raw);
            assert_eq!(got, "other", "{raw:?} -> {got}");
        }
    }

    #[test]
    fn known_clients_and_aliases_map_to_the_enum() {
        assert_eq!(normalize_mcp_client("claude-code"), "claude_code");
        assert_eq!(normalize_mcp_client("Claude Code"), "claude_code");
        assert_eq!(normalize_mcp_client("claude"), "claude_code");
        assert_eq!(normalize_mcp_client("Claude Desktop"), "claude_desktop");
        assert_eq!(normalize_mcp_client("Visual Studio Code"), "vscode");
        assert_eq!(normalize_mcp_client("opencode"), "opencode");
    }

    #[test]
    fn the_names_agents_actually_send_are_recognized() {
        // Captured on the wire (issue #527 QA), one per agent.
        assert_eq!(normalize_mcp_client("codex-mcp-client"), "codex");
        assert_eq!(normalize_mcp_client("openclaw-bundle-mcp"), "openclaw");
        assert_eq!(normalize_mcp_client("pi-mcp-cosmonic"), "pi");
        assert_eq!(normalize_mcp_client("opencode"), "opencode");
        assert_eq!(normalize_mcp_client("claude-code"), "claude_code");
        // Hermes sends the Python SDK default; nothing to recognize.
        assert_eq!(normalize_mcp_client("mcp"), "other");
    }

    #[test]
    fn the_title_is_a_fallback_never_an_override() {
        assert_eq!(
            normalize_mcp_client_info("codex-mcp-client", Some("Codex")),
            "codex"
        );
        assert_eq!(normalize_mcp_client_info("mcp", Some("Codex")), "codex");
        assert_eq!(normalize_mcp_client_info("mcp", None), "other");
        assert_eq!(
            normalize_mcp_client_info("mcp", Some("/Users/bob/agent")),
            "other"
        );
        // A recognized name wins over a title that says otherwise.
        assert_eq!(
            normalize_mcp_client_info("opencode", Some("Codex")),
            "opencode"
        );
        for (n, t) in [("mcp", Some("Codex")), ("x", Some("y")), ("pi-mcp-z", None)] {
            assert!(MCP_CLIENTS.contains(&normalize_mcp_client_info(n, t)));
        }
    }

    #[test]
    fn every_result_is_in_the_allowlist() {
        // A value outside MCP_CLIENTS is dropped by the catalog, so the event
        // would vanish with nothing to show for it.
        for raw in ["claude-code", "nonsense", "", "cursor_ide", "windsurf-ide"] {
            assert!(
                MCP_CLIENTS.contains(&normalize_mcp_client(raw)),
                "{raw:?} produced a value the catalog would reject"
            );
        }
    }

    /// A deterministic environment: the tests never read the real one.
    fn env_of<'a>(pairs: &'a [(&'a str, &'a str)]) -> impl Fn(&str) -> Option<String> + 'a {
        move |k| {
            pairs
                .iter()
                .find(|(n, _)| *n == k)
                .map(|(_, v)| v.to_string())
        }
    }

    #[test]
    fn nothing_set_is_none_and_is_not_an_agent() {
        let got = detect_agent_harness(env_of(&[]));
        assert_eq!(got, "none");
        assert!(!is_agent(got));
    }

    #[test]
    fn a_marker_names_its_harness_and_the_value_never_travels() {
        // `Any` markers: the value is a session id / a token and is irrelevant.
        for (var, want) in [
            ("CLAUDECODE", "claude_code"),
            ("CLAUDE_CODE", "claude_code"),
            ("CODEX_THREAD_ID", "codex"),
            ("HERMES_SESSION_ID", "hermes"),
            ("PI_CODING_AGENT", "pi"),
            ("OPENCODE_CLIENT", "opencode"),
            ("OPENCLAW_SHELL", "openclaw"),
            ("GEMINI_CLI", "gemini_cli"),
            ("CURSOR_AGENT", "cursor_cli"),
            ("COPILOT_GITHUB_TOKEN", "github_copilot"),
        ] {
            let secret = "ghp_thisIsATokenValueThatMustNeverAppear";
            let got = detect_agent_harness(env_of(&[(var, secret)]));
            assert_eq!(got, want, "{var}");
            assert!(!got.contains("ghp_"));
            assert!(AGENT_HARNESSES.contains(&got));
        }
    }

    #[test]
    fn local_markers_cover_what_the_registry_misses() {
        // opencode as an MCP host: `OPENCODE=1` + `AGENT=1`, no OPENCODE_CLIENT.
        assert_eq!(
            detect_agent_harness(env_of(&[("OPENCODE", "1"), ("AGENT", "1")])),
            "opencode"
        );
        for (label, _, _) in LOCAL_MARKERS {
            assert!(
                AGENT_HARNESSES.contains(label),
                "local marker for unknown label {label}"
            );
        }
    }

    #[test]
    fn what_each_agent_actually_hands_an_mcp_server() {
        // The environments captured in the issue #527 QA, one per harness.
        // Claude Code: its marker plus a versioned standard var that is NOT
        // the bare id — the marker is what carries it.
        assert_eq!(
            detect_agent_harness(env_of(&[
                ("CLAUDECODE", "1"),
                ("AI_AGENT", "claude-code_2-1-273_agent")
            ])),
            "claude_code"
        );
        // Pi: both a marker and an exact standard var.
        assert_eq!(
            detect_agent_harness(env_of(&[("PI_CODING_AGENT", "true"), ("AI_AGENT", "pi")])),
            "pi"
        );
        // Codex scrubs the environment it hands MCP servers: nothing to see,
        // and `clientInfo` is the signal for it.
        assert_eq!(
            detect_agent_harness(env_of(&[("HOME", "/Users/x"), ("PATH", "/bin")])),
            "none"
        );
    }

    #[test]
    fn an_empty_marker_is_not_set() {
        assert_eq!(detect_agent_harness(env_of(&[("CLAUDECODE", "")])), "none");
    }

    #[test]
    fn exact_patterns_need_the_exact_value() {
        assert_eq!(detect_agent_harness(env_of(&[("VTCODE", "1")])), "vtcode");
        assert_eq!(detect_agent_harness(env_of(&[("VTCODE", "true")])), "none");
        assert_eq!(
            detect_agent_harness(env_of(&[("TERM_PROGRAM", "WarpTerminal")])),
            "warp"
        );
        assert_eq!(
            detect_agent_harness(env_of(&[("TERM_PROGRAM", "iTerm.app")])),
            "none"
        );
    }

    #[test]
    fn registry_order_decides_first_match() {
        // Cowork runs on top of Claude Code and sets both markers; it is listed
        // first upstream so it wins. Same for Cursor CLI inside Cursor.
        assert_eq!(
            detect_agent_harness(env_of(&[
                ("CLAUDECODE", "1"),
                ("CLAUDE_CODE_IS_COWORK", "1")
            ])),
            "cowork"
        );
        assert_eq!(
            detect_agent_harness(env_of(&[("CURSOR_TRACE_ID", "abc"), ("CURSOR_AGENT", "1")])),
            "cursor_cli"
        );
        // A claude-code session inside a Warp terminal is claude-code: the
        // agent entries precede the terminal entries.
        assert_eq!(
            detect_agent_harness(env_of(&[
                ("TERM_PROGRAM", "WarpTerminal"),
                ("CLAUDECODE", "1")
            ])),
            "claude_code"
        );
    }

    #[test]
    fn standard_vars_follow_hf_semantics() {
        // Exact id at walk time.
        assert_eq!(
            detect_agent_harness(env_of(&[("AI_AGENT", "codex")])),
            "codex"
        );
        assert_eq!(
            detect_agent_harness(env_of(&[("AGENT", " hermes-agent ")])),
            "hermes"
        );
        // A case variant of a known id is recognized after the walk.
        assert_eq!(
            detect_agent_harness(env_of(&[("AI_AGENT", "Claude-Code")])),
            "claude_code"
        );
        // A marker beats a standard var that names something else.
        assert_eq!(
            detect_agent_harness(env_of(&[("AI_AGENT", "codex"), ("CLAUDECODE", "1")])),
            "claude_code"
        );
        // Anything else is `unknown` — the raw value never travels.
        for raw in ["acme-agent", "/Users/bob/bin/agent", "🙂"] {
            let got = detect_agent_harness(env_of(&[("AI_AGENT", raw)]));
            assert_eq!(got, "unknown", "{raw:?}");
        }
        assert_eq!(detect_agent_harness(env_of(&[("AI_AGENT", "   ")])), "none");
    }

    #[test]
    fn every_registry_entry_maps_into_the_allowlist() {
        // The catalog's per-property allowlist is AGENT_HARNESSES; a label
        // outside it would drop the whole event with nothing to show for it.
        for h in REGISTRY {
            assert!(
                AGENT_HARNESSES.contains(&h.label),
                "{} -> {}",
                h.id,
                h.label
            );
            assert!(
                h.label
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
                "label not snake_case: {}",
                h.label
            );
            for (var, pat) in h.env_vars {
                let value = match pat {
                    Match::Any => "s3cret-session-id",
                    Match::Exact(v) => v,
                };
                let got = detect_agent_harness(env_of(&[(var, value)]));
                assert!(AGENT_HARNESSES.contains(&got), "{var} -> {got}");
                assert!(!got.contains("s3cret"));
            }
        }
        assert!(AGENT_HARNESSES.contains(&HARNESS_NONE));
        assert!(AGENT_HARNESSES.contains(&HARNESS_UNKNOWN));
        assert_eq!(AGENT_HARNESSES.len(), REGISTRY.len() + 2);
        let mut labels: Vec<_> = AGENT_HARNESSES.to_vec();
        labels.sort_unstable();
        labels.dedup();
        assert_eq!(labels.len(), AGENT_HARNESSES.len(), "duplicate label");
    }

    #[test]
    fn harness_labels_share_the_client_spelling_where_they_overlap() {
        // The whole point of a second signal is comparing it to the first:
        // `client == harness` must be a meaningful test in Amplitude.
        for shared in [
            "claude_code",
            "cursor",
            "hermes",
            "openclaw",
            "opencode",
            "codex",
        ] {
            assert!(MCP_CLIENTS.contains(&shared), "{shared} left MCP_CLIENTS");
            assert!(
                AGENT_HARNESSES.contains(&shared),
                "{shared} not a harness label"
            );
        }
        for cli in ["gemini_cli", "cursor_cli", "pi"] {
            assert!(
                AGENT_HARNESSES.contains(&cli),
                "{cli} spelled differently from AGENT_CLIS"
            );
        }
    }

    #[test]
    fn ambient_terminals_and_ides_are_not_agents() {
        for h in AMBIENT_HARNESSES {
            assert!(
                AGENT_HARNESSES.contains(h),
                "ambient entry {h} is not a label"
            );
            assert!(!is_agent(h));
        }
        assert!(is_agent("claude_code"));
        assert!(is_agent("cursor_cli"));
        assert!(
            is_agent("unknown"),
            "something announced itself as an agent"
        );
        assert!(!is_agent("none"));
    }

    #[test]
    fn only_the_major_version_travels() {
        assert_eq!(version_major("1.2.3"), "1");
        assert_eq!(version_major("v2.0.0-beta.1"), "2");
        assert_eq!(version_major("2026.09.06"), "2026");
        assert_eq!(version_major("not-a-version"), "unknown");
        assert_eq!(version_major(""), "unknown");
    }

    #[test]
    fn buckets_cover_their_ranges_without_gaps() {
        assert_eq!(session_secs(0), "<1m");
        assert_eq!(session_secs(59), "<1m");
        assert_eq!(session_secs(60), "1-10m");
        assert_eq!(session_secs(3_600), "1-8h");
        assert_eq!(session_secs(u64::MAX), "8h+");
        assert_eq!(count_results(0), "0");
        assert_eq!(count_results(5), "1-5");
        assert_eq!(count_results(6), "6-20");
        assert_eq!(count_results(u64::MAX), "21+");
    }
}
