//! Skills over MCP (`io.modelcontextprotocol/skills`) — progressive disclosure.
//!
//! The `cosmonic_*` tools are the hands; a **skill** is the manual. Without one,
//! a model faces 33 tools and has to infer the scaffold → build → publish →
//! apply → verify loop, the deny-all egress default, and the P2/P3 handler
//! distinction from tool descriptions alone. With one, it reads a playbook.
//!
//! Skills already ship as *installed* files — `~/.claude/skills/…` and the
//! per-agent equivalents, vendored per platform and kept current by
//! `src/main/agents.js`'s `autoUpdate()`. Serving them here means **connecting
//! to this server is enough**: every MCP client gets the playbook, including
//! the ones with no skills directory at all (LM Studio, NVIDIA OpenShell), and
//! an install that has gone stale is bypassed.
//!
//! ## The extension rides on `resources`
//!
//! There is no skills method in MCP — progressive disclosure is an extension
//! still in review (the current revision is 2026-07-28). So this uses the
//! **resources** primitive, which every client we support already speaks,
//! including ones still on 2025-06-18. Discovery is three tiers:
//!
//! 1. A client reads [`INDEX_URI`] (`skill://index.json`) once at session
//!    start: names plus the trigger descriptions it matches requests against.
//!    ~2 KB for the whole catalog.
//! 2. Only when a request matches does it read `skill://<name>/SKILL.md` —
//!    the playbook, tens of KB.
//! 3. Relative Markdown links inside a `SKILL.md` resolve against the skill
//!    root, so `[Templates](references/templates.md)` is
//!    `skill://<name>/references/templates.md`, pulled only at that depth.
//!
//! Reading all four playbooks and every reference would be ~276 KB. Reading the
//! index is ~2 KB. That gap is the entire point.
//!
//! ## Why `include_str!`
//!
//! The daemon runs as a service, with no dependency on the Electron app's
//! resource directory, and must work air-gapped. Embedding also makes drift
//! impossible: a playbook documenting a tool this binary does not have cannot
//! ship, because both come from the same build.
//!
//! ## Security
//!
//! [`read`] resolves a URI by matching it **verbatim** against the static
//! [`SKILLS`] table. There is no filesystem lookup, so there is no path
//! traversal to defend against — `skill://x/../../etc/passwd` simply matches
//! nothing and returns `None`. Keep it that way: if this ever reads from disk,
//! it needs a canonicalize-and-contain check first.
//!
//! ## Adding or updating a skill
//!
//! Don't edit `skills/` or the generated table by hand. `agent-integrations`
//! is the source of truth; run `node scripts/vendor-daemon-skills.mjs` and
//! commit the diff.

use rmcp::model::{Resource, ResourceTemplate};
use serde_json::json;

/// Identifier of the MCP skills extension these resources implement.
pub const EXTENSION_ID: &str = "io.modelcontextprotocol/skills";

/// URI of the skill catalog clients read at session start.
pub const INDEX_URI: &str = "skill://index.json";

/// Scheme prefix for every skill resource URI.
const SCHEME: &str = "skill://";

/// The entrypoint filename of a skill bundle, per the SKILL.md convention.
const ENTRY: &str = "SKILL.md";

/// A supporting file inside a skill bundle, served at `skill://<skill>/<path>`.
pub struct SkillFile {
    /// Path relative to the skill root, e.g. `references/templates.md`.
    /// Matched verbatim against the requested URI.
    pub path: &'static str,
    /// File contents, embedded at compile time.
    pub text: &'static str,
    /// MIME type reported to the client.
    pub mime_type: &'static str,
}

/// One skill: a `SKILL.md` playbook and its supporting files.
pub struct Skill {
    /// Skill name; the authority segment of its URIs, and the name the same
    /// skill has when installed on disk.
    pub name: &'static str,
    /// The playbook, served at `skill://<name>/SKILL.md`. Its own field rather
    /// than one of `files` so a skill structurally cannot exist without it.
    pub skill_md: &'static str,
    /// Supporting files, if any.
    pub files: &'static [SkillFile],
}

/// The version of `agent-integrations` these skills were vendored from.
// BEGIN SKILLS (generated by scripts/vendor-daemon-skills.mjs — do not edit by hand)
pub const SKILLS_VERSION: &str = "1.0.0";

pub static SKILLS: &[Skill] = &[
    Skill {
        name: "cosmonic-sandbox",
        skill_md: include_str!("../skills/cosmonic-sandbox/SKILL.md"),
        files: &[
            SkillFile {
                path: "references/composition.md",
                text: include_str!("../skills/cosmonic-sandbox/references/composition.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/crds.md",
                text: include_str!("../skills/cosmonic-sandbox/references/crds.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/http-trigger.md",
                text: include_str!("../skills/cosmonic-sandbox/references/http-trigger.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/local-ai.md",
                text: include_str!("../skills/cosmonic-sandbox/references/local-ai.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/mcp-servers.md",
                text: include_str!("../skills/cosmonic-sandbox/references/mcp-servers.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/oci-registry.md",
                text: include_str!("../skills/cosmonic-sandbox/references/oci-registry.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/patterns-and-smoke-tests.md",
                text: include_str!(
                    "../skills/cosmonic-sandbox/references/patterns-and-smoke-tests.md"
                ),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/recipes.md",
                text: include_str!("../skills/cosmonic-sandbox/references/recipes.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/templates.md",
                text: include_str!("../skills/cosmonic-sandbox/references/templates.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/wasm-crate-compat.md",
                text: include_str!("../skills/cosmonic-sandbox/references/wasm-crate-compat.md"),
                mime_type: "text/markdown",
            },
        ],
    },
    Skill {
        name: "cosmonic-go",
        skill_md: include_str!("../skills/cosmonic-go/SKILL.md"),
        files: &[SkillFile {
            path: "references/upstream.md",
            text: include_str!("../skills/cosmonic-go/references/upstream.md"),
            mime_type: "text/markdown",
        }],
    },
    Skill {
        name: "cosmonic-nats",
        skill_md: include_str!("../skills/cosmonic-nats/SKILL.md"),
        files: &[
            SkillFile {
                path: "references/nats-concepts.md",
                text: include_str!("../skills/cosmonic-nats/references/nats-concepts.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/nats-jetstream.md",
                text: include_str!("../skills/cosmonic-nats/references/nats-jetstream.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/nats-security.md",
                text: include_str!("../skills/cosmonic-nats/references/nats-security.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/nats-server.md",
                text: include_str!("../skills/cosmonic-nats/references/nats-server.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/patterns.md",
                text: include_str!("../skills/cosmonic-nats/references/patterns.md"),
                mime_type: "text/markdown",
            },
            SkillFile {
                path: "references/wasmcloud-nats.md",
                text: include_str!("../skills/cosmonic-nats/references/wasmcloud-nats.md"),
                mime_type: "text/markdown",
            },
        ],
    },
    Skill {
        name: "cosmonic-nats-tuning",
        skill_md: include_str!("../skills/cosmonic-nats-tuning/SKILL.md"),
        files: &[SkillFile {
            path: "references/nats-tuning.md",
            text: include_str!("../skills/cosmonic-nats-tuning/references/nats-tuning.md"),
            mime_type: "text/markdown",
        }],
    },
];
// END SKILLS

impl Skill {
    /// URI of this skill's `SKILL.md`.
    pub fn entry_uri(&self) -> String {
        format!("{SCHEME}{}/{ENTRY}", self.name)
    }

    /// URI of a supporting file.
    pub fn file_uri(&self, file: &SkillFile) -> String {
        format!("{SCHEME}{}/{}", self.name, file.path)
    }

    /// The `description` from the frontmatter — the trigger text a client
    /// matches user requests against.
    pub fn description(&self) -> &'static str {
        frontmatter_field(self.skill_md, "description").unwrap_or("")
    }
}

/// The skill catalog served at [`INDEX_URI`].
///
/// Built from [`SKILLS`] on every read rather than stored, so the catalog
/// cannot fall out of step with the embedded files.
pub fn index_json() -> String {
    let skills: Vec<_> = SKILLS
        .iter()
        .map(|skill| {
            json!({
                "name": skill.name,
                "description": skill.description(),
                "uri": skill.entry_uri(),
                "files": skill
                    .files
                    .iter()
                    .map(|file| json!({
                        "path": file.path,
                        "uri": skill.file_uri(file),
                        "mimeType": file.mime_type,
                    }))
                    .collect::<Vec<_>>(),
            })
        })
        .collect();

    let index = json!({
        "schemaVersion": "1",
        "extension": EXTENSION_ID,
        "server": {
            "name": "cosmonic-desktop",
            "version": env!("CARGO_PKG_VERSION"),
            "skillsVersion": SKILLS_VERSION,
        },
        "usage": "Read the SKILL.md of whichever skill's description matches the task, then only \
                  the reference files its body points you at. A playbook names those files by \
                  their path relative to the skill root (for example `references/recipes.md`, \
                  written as if on disk); read one here as skill://<skill>/<that path>. Every \
                  such path is listed under this skill's `files`.",
        "skills": skills,
    });
    // Built from &'static str and owned Vecs, so serialization cannot fail —
    // but never panic in the daemon over a resource read.
    serde_json::to_string_pretty(&index).unwrap_or_else(|_| String::from(r#"{"skills":[]}"#))
}

/// Every skill resource, for `resources/list`.
///
/// The index is listed with a description that tells a client to read it FIRST
/// and the playbooks only on a match — the whole catalog is otherwise just a
/// list of large files, and a client that reads them all has paid 276 KB for
/// what progressive disclosure exists to avoid.
pub fn resources() -> Vec<Resource> {
    let mut out = vec![Resource::new(INDEX_URI, "skill-index")
        .with_title("Skill catalog")
        .with_description(
            "Catalog of the skills this server publishes: name, trigger description, and the \
             URI of each SKILL.md. Read this first, then read only the skills whose \
             descriptions match the task.",
        )
        .with_mime_type("application/json")];

    for skill in SKILLS {
        out.push(
            Resource::new(skill.entry_uri(), skill.name)
                .with_title(format!("{} skill", skill.name))
                .with_description(format!(
                    "{}\n\nThis playbook names its supporting files by path relative to the \
                     skill root (e.g. `references/recipes.md`); read one as \
                     skill://{}/<that path>.",
                    skill.description(),
                    skill.name
                ))
                .with_mime_type("text/markdown")
                .with_size(clamp_size(skill.skill_md.len())),
        );
        for file in skill.files {
            out.push(
                Resource::new(
                    skill.file_uri(file),
                    format!("{}/{}", skill.name, file.path),
                )
                .with_title(format!("{} — {}", skill.name, file.path))
                .with_description(format!(
                    "Supporting file for the {} skill, linked from its SKILL.md.",
                    skill.name
                ))
                .with_mime_type(file.mime_type)
                .with_size(clamp_size(file.text.len())),
            );
        }
    }
    out
}

/// RFC 6570 templates for `resources/templates/list`, so a client can build a
/// skill URI without enumerating every resource.
pub fn resource_templates() -> Vec<ResourceTemplate> {
    vec![
        ResourceTemplate::new("skill://{skill}/SKILL.md", "skill-playbook")
            .with_title("Skill playbook")
            .with_description(
                "The SKILL.md of a named skill. Skill names come from skill://index.json.",
            )
            .with_mime_type("text/markdown"),
        ResourceTemplate::new("skill://{skill}/{+path}", "skill-file")
            .with_title("Skill supporting file")
            .with_description(
                "A file bundled with a skill. Relative Markdown links inside a SKILL.md resolve \
                 against the skill root and produce these URIs.",
            ),
    ]
}

/// Resolve a `skill://` URI to `(mime_type, contents)`, or `None` when this
/// server serves nothing there.
///
/// Verbatim table lookup — see the module docs on why that is the security
/// property, not an implementation detail.
pub fn read(uri: &str) -> Option<(&'static str, String)> {
    if uri == INDEX_URI {
        return Some(("application/json", index_json()));
    }
    let (name, path) = uri.strip_prefix(SCHEME)?.split_once('/')?;
    let skill = SKILLS.iter().find(|skill| skill.name == name)?;
    if path == ENTRY {
        return Some(("text/markdown", skill.skill_md.to_owned()));
    }
    let file = skill.files.iter().find(|file| file.path == path)?;
    Some((file.mime_type, file.text.to_owned()))
}

/// `Resource.size` is a `u32`; saturate rather than wrap on a hypothetical
/// >4 GiB file, so a size can never be reported as a small number.
fn clamp_size(len: usize) -> u64 {
    // rmcp 3 widened `Resource::size` from u32 to u64; the clamp stays because
    // the field is advisory and a usize on a 128-bit-address future should not
    // panic here.
    u64::try_from(len).unwrap_or(u64::MAX)
}

/// Read a single-line field out of a Markdown file's YAML frontmatter.
///
/// Deliberately minimal — a YAML parser would be a large dependency for one
/// field. SKILL.md frontmatter keeps `name` and `description` on one line each
/// (optionally quoted), which is what the SKILL.md convention prescribes
/// anyway; `scripts/vendor-daemon-skills.mjs` fails the vendor when a skill
/// arrives without a single-line `description`, so a silently empty trigger
/// cannot reach the catalog.
fn frontmatter_field(markdown: &'static str, field: &str) -> Option<&'static str> {
    // CRLF-tolerant. Git checks these files out with CRLF on Windows, and a
    // parser that only knew `---\n` returned None for every field there — so
    // every skill's trigger description was the empty string on Windows, which
    // publishes a skill no model can ever match. The catalog looks fine; only
    // the matching silently stops working.
    let body = markdown
        .strip_prefix("---\n")
        .or_else(|| markdown.strip_prefix("---\r\n"))?;
    let end = body.find("\n---")?;
    for line in body[..end].lines() {
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        if key.trim() != field {
            continue;
        }
        let value = value.trim().trim_end_matches('\r');
        let unquoted = value
            .strip_prefix('"')
            .and_then(|rest| rest.strip_suffix('"'))
            .or_else(|| {
                value
                    .strip_prefix('\'')
                    .and_then(|rest| rest.strip_suffix('\''))
            })
            .unwrap_or(value);
        return Some(unquoted);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    #[test]
    fn every_skill_has_a_playbook_and_a_trigger_description() {
        assert!(!SKILLS.is_empty(), "the vendor step produced no skills");
        for skill in SKILLS {
            assert!(
                skill.skill_md.starts_with("---\n") || skill.skill_md.starts_with("---\r\n"),
                "{}: SKILL.md has no frontmatter",
                skill.name
            );
            // The description IS the trigger: an empty one publishes a skill no
            // model can ever match, which looks like the feature working.
            let description = skill.description();
            assert!(
                description.len() > 40,
                "{}: description is {} chars — too short to match a request on",
                skill.name,
                description.len()
            );
        }
    }

    #[test]
    fn skill_names_are_unique() {
        // `read()` resolves by first match, so a duplicate name would shadow a
        // whole skill's files with no error anywhere.
        let mut names: Vec<_> = SKILLS.iter().map(|s| s.name).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(before, names.len(), "duplicate skill name in SKILLS");
    }

    #[test]
    fn the_index_is_small_enough_to_read_at_session_start() {
        // The whole point of progressive disclosure: the catalog is read on
        // EVERY session, the playbooks only on a match. If the index ever
        // approaches the size of the bodies it indexes, the tiering is gone.
        let index = index_json();
        let bodies: usize = SKILLS
            .iter()
            .map(|s| s.skill_md.len() + s.files.iter().map(|f| f.text.len()).sum::<usize>())
            .sum();
        assert!(
            index.len() < 24 * 1024,
            "skill index is {} bytes; keep it readable at session start",
            index.len()
        );
        assert!(
            index.len() * 8 < bodies,
            "index ({}) is not much cheaper than reading everything ({bodies})",
            index.len()
        );
    }

    #[test]
    fn the_index_advertises_only_uris_that_resolve() {
        let index: Value = serde_json::from_str(&index_json()).expect("index is JSON");
        assert_eq!(index["extension"], Value::from(EXTENSION_ID));
        let skills = index["skills"].as_array().expect("skills array");
        assert_eq!(skills.len(), SKILLS.len());
        for entry in skills {
            let uri = entry["uri"].as_str().unwrap();
            assert!(read(uri).is_some(), "index advertises unreadable {uri}");
            for file in entry["files"].as_array().unwrap() {
                let uri = file["uri"].as_str().unwrap();
                assert!(read(uri).is_some(), "index advertises unreadable {uri}");
            }
        }
    }

    #[test]
    fn every_listed_resource_reads() {
        // index + one playbook per skill, at minimum.
        assert!(
            resources().len() > SKILLS.len(),
            "resources() is suspiciously small"
        );
        for resource in resources() {
            let uri = &resource.uri;
            let (mime, body) = read(uri).unwrap_or_else(|| panic!("listed but unreadable: {uri}"));
            assert!(!body.is_empty(), "{uri} is empty");
            // resources/list must report the same type resources/read returns,
            // or a client that keys off it re-parses the body.
            if let Some(listed) = &resource.mime_type {
                assert_eq!(listed, mime, "mime mismatch on {uri}");
            }
        }
    }

    /// Relative Markdown links inside a SKILL.md become `skill://` URIs — that
    /// is what makes the third disclosure tier work. A link to a file we did
    /// not embed is a resource the model will ask for and not get, and it fails
    /// silently: the model just proceeds without the reference it wanted.
    ///
    /// `scripts/vendor-daemon-skills.mjs` refuses to vendor a dangling link;
    /// this is the same check on the compiled-in copy, so hand-editing
    /// `skills/` cannot bypass it either.
    /// Reference paths a playbook names that this server does not serve.
    ///
    /// Resolution is CROSS-SKILL on purpose: `cosmonic-go` says "see
    /// `cosmonic-sandbox` `references/composition.md`", and that file is served
    /// — under another skill. Checking only the naming skill would call a
    /// working reference broken.
    ///
    /// Only skill-bundle paths count. `references/…` and `…/SKILL.md` are ours;
    /// a path like `docs/tuning.md` in "each scaffold's `docs/tuning.md`" is a
    /// file in the USER's generated project, which no MCP resource ever backs.
    fn unserved_references() -> Vec<String> {
        let mut out = Vec::new();
        for skill in SKILLS {
            for target in referenced_files(skill.skill_md) {
                if target.contains(':') || target.starts_with('/') {
                    continue; // absolute or external — not ours to serve
                }
                let path = target.trim_start_matches("./");
                let bundle_path = path.starts_with("references/") || path.ends_with("SKILL.md");
                if !bundle_path {
                    continue;
                }
                let served = SKILLS
                    .iter()
                    .any(|s| read(&format!("{SCHEME}{}/{path}", s.name)).is_some());
                if !served {
                    out.push(format!("{}: {path}", skill.name));
                }
            }
        }
        out.sort();
        out.dedup();
        out
    }

    /// Paths a playbook names that this server cannot serve — a ratchet, not a
    /// suppression. Each entry is a real gap in the MCP surface: a model told to
    /// read the file gets nothing back, silently, and carries on without it.
    ///
    /// Fixes belong upstream in `agent-integrations` (issue #501 phase 7); when
    /// one lands and is re-vendored, this test FAILS until the entry is removed,
    /// so the list can only ever shrink.
    const KNOWN_UNSERVED: &[&str] = &[
        // The authoring guide for building MCP servers is not part of the
        // client-facing skill set, so nothing serves it over MCP. Upstream
        // should fold what a deploying agent needs into
        // cosmonic-sandbox/references/mcp-servers.md and drop the pointer.
        "cosmonic-sandbox: skills/building-mcp-servers/SKILL.md",
    ];

    #[test]
    fn no_skill_points_at_a_file_that_is_not_served() {
        // Relative paths inside a playbook become skill:// URIs — that is what
        // makes the third disclosure tier work. A path we do not serve fails
        // SILENTLY: the model asks, gets nothing, and proceeds without the
        // detail it wanted.
        let unserved = unserved_references();
        let unexpected: Vec<_> = unserved
            .iter()
            .filter(|u| !KNOWN_UNSERVED.contains(&u.as_str()))
            .collect();
        assert!(
            unexpected.is_empty(),
            "playbooks point at files this server does not serve: {unexpected:?}"
        );
        let fixed: Vec<_> = KNOWN_UNSERVED
            .iter()
            .filter(|k| !unserved.iter().any(|u| u == *k))
            .collect();
        assert!(
            fixed.is_empty(),
            "these are served now — drop them from KNOWN_UNSERVED: {fixed:?}"
        );
    }

    #[test]
    fn the_reference_check_actually_examines_references() {
        // Without this the suite passes when `referenced_files` stops matching.
        // It did: the first version understood only `[text](path.md)` links and
        // examined ZERO paths across all four skills, because the playbooks name
        // their files as backticked paths instead.
        let examined: usize = SKILLS
            .iter()
            .map(|s| referenced_files(s.skill_md).len())
            .sum();
        assert!(
            examined >= 4 * SKILLS.len(),
            "only {examined} reference paths found across {} skills; the extractor is broken",
            SKILLS.len()
        );
        // And it must resolve most of them, or "serving skills" is a fiction.
        assert!(
            unserved_references().len() <= KNOWN_UNSERVED.len(),
            "more unserved references than the known set"
        );
    }

    /// Every `.md` file a playbook points a reader at.
    ///
    /// Two forms, because the skills use both. Markdown links —
    /// `[Recipes](references/recipes.md)` — and, far more often, a backticked
    /// path written as if on disk: `` `references/recipes.md` ``. The second is
    /// the Agent Skills convention (an installed skill IS a directory), and it
    /// is why a link check that only understood `](...)` silently examined
    /// ZERO links across all four skills while passing.
    fn referenced_files(markdown: &str) -> Vec<String> {
        let mut out = Vec::new();

        let mut rest = markdown;
        while let Some(open) = rest.find("](") {
            rest = &rest[open + 2..];
            let Some(close) = rest.find(')') else { break };
            let target = rest[..close].split(['#', ' ']).next().unwrap_or("");
            if target.ends_with(".md") {
                out.push(target.to_string());
            }
            rest = &rest[close..];
        }

        for span in markdown.split('`').skip(1).step_by(2) {
            // A backtick span is a path only if it is one: no spaces, ends .md.
            let target = span.split(['#', ' ']).next().unwrap_or("");
            if target.ends_with(".md") && !target.contains(char::is_whitespace) {
                out.push(target.to_string());
            }
        }
        out.sort();
        out.dedup();
        out
    }

    /// The security property: `read` is a verbatim lookup in a static table.
    /// There is no filesystem call, so a traversal-shaped URI matches nothing.
    /// If this ever reads from disk it needs a canonicalize-and-contain check
    /// FIRST — these cases are the tripwire for that change.
    #[test]
    fn read_resolves_nothing_outside_the_static_table() {
        let name = SKILLS[0].name;
        for uri in [
            &format!("skill://{name}/../../../etc/passwd"),
            &format!("skill://{name}/./SKILL.md"),
            &format!("skill://{name}/references/../SKILL.md"),
            &format!("skill://{name}/SKILL.md/"),
            &format!("skill://{name}//SKILL.md"),
            &format!("skill://{name}/skill.md"), // case matters
            "skill://../SKILL.md",
            "skill://index.json/../SKILL.md",
            "skill:///SKILL.md",
            "file:///etc/passwd",
            "skill://",
            "",
        ] {
            assert!(read(uri).is_none(), "resolved something for {uri:?}");
        }
    }

    #[test]
    fn read_serves_the_index_and_each_playbook() {
        let (mime, body) = read(INDEX_URI).expect("index");
        assert_eq!(mime, "application/json");
        assert!(serde_json::from_str::<Value>(&body).is_ok());
        for skill in SKILLS {
            let (mime, body) = read(&skill.entry_uri()).expect("playbook");
            assert_eq!(mime, "text/markdown");
            assert_eq!(body, skill.skill_md);
        }
    }

    #[test]
    fn resource_templates_cover_both_tiers() {
        let templates = resource_templates();
        let uris: Vec<_> = templates.iter().map(|t| t.uri_template.as_str()).collect();
        assert!(uris.contains(&"skill://{skill}/SKILL.md"));
        assert!(uris.contains(&"skill://{skill}/{+path}"));
    }

    #[test]
    fn referenced_files_finds_both_link_and_backticked_paths() {
        let doc = "see [a](references/a.md) and [b](./references/b.md#anchor), \
                   [ext](https://x.test/c.md), [img](d.png), and `references/e.md` \
                   plus `not a path.md` and `code.rs`";
        let links = referenced_files(doc);
        assert!(links.contains(&"references/a.md".to_string()));
        assert!(links.contains(&"./references/b.md".to_string()));
        assert!(
            links.contains(&"references/e.md".to_string()),
            "backticked path missed"
        );
        assert!(links.contains(&"https://x.test/c.md".to_string()));
        assert!(
            !links.iter().any(|l| l.contains(' ')),
            "prose captured: {links:?}"
        );
        assert!(!links.contains(&"code.rs".to_string()));
        assert!(!links.contains(&"d.png".to_string()));
    }

    #[test]
    fn frontmatter_field_reads_a_crlf_checkout() {
        // Windows git checks these out with CRLF. A parser that only knew LF
        // returned None for every field, so every trigger description was ""
        // there — a skill published that no request can match.
        const CRLF: &str = "---\r\nname: demo\r\ndescription: a windows one\r\n---\r\nbody\r\n";
        assert_eq!(frontmatter_field(CRLF, "name"), Some("demo"));
        assert_eq!(
            frontmatter_field(CRLF, "description"),
            Some("a windows one")
        );
        const CRLF_QUOTED: &str = "---\r\ndescription: \"quoted\"\r\n---\r\nbody\r\n";
        assert_eq!(
            frontmatter_field(CRLF_QUOTED, "description"),
            Some("quoted")
        );
    }

    #[test]
    fn frontmatter_field_handles_quoting_and_absence() {
        const DOC: &str = "---\nname: demo\ndescription: \"a quoted one\"\n---\nbody\n";
        assert_eq!(frontmatter_field(DOC, "name"), Some("demo"));
        assert_eq!(frontmatter_field(DOC, "description"), Some("a quoted one"));
        assert_eq!(frontmatter_field(DOC, "missing"), None);
        assert_eq!(frontmatter_field("no frontmatter\n", "name"), None);
        assert_eq!(
            frontmatter_field("---\nunterminated: x\n", "unterminated"),
            None
        );
    }

    #[test]
    fn the_vendored_version_is_recorded() {
        // A catalog that reports 0.0.0 means the generated region was never
        // populated — the include_str! table would be empty too.
        assert_ne!(SKILLS_VERSION, "0.0.0", "skills were never vendored");
    }
}
